# ansible playbook: server_config.yml
# Usage: $ ansible-playbook server_config.yml
# Note: see [inventory] and [ansible.cfg] for preset details

---

- name: Web Servers Configuration
  hosts: web_servers
  become: yes
  tasks:
    - name: Update package cache for Ubuntu
      when: ansible_os_family == 'Debian'
      apt:
        update_cache: yes
      register: ubuntu_update_result

    - name: Update package cache for Oracle Linux
      when: ansible_os_family == 'RedHat'
      yum:
        update_cache: yes
      register: oraclelinux_update_result

    - name: Display update results for Ubuntu
      when: ubuntu_update_result is defined and ubuntu_update_result.changed
      debug:
        msg: "Package cache updated for Ubuntu."

    - name: Display update results for Oracle Linux
      when: oraclelinux_update_result is defined and oraclelinux_update_result.changed
      debug:
        msg: "Package cache updated for Oracle Linux."

    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install PHP on Apache
      apt:
        name: php
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache on OracleLinux
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "OracleLinux"

    - name: Start and enable Apache on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Apache on OracleLinux
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "OracleLinux"
