# Ansible Playbook: server_config.yml
# This playbook is designed to configure various types of servers, including web servers, database servers, and file servers.
# Usage: $ ansible-playbook server_config.yml
# Note: see [inventory] and [ansible.cfg] for preset details

---
- name: Base configuration
  hosts: all
  become: true
  roles:
    - base


- name: Web Servers Configuration
  hosts: web_servers
  become: yes
  roles:
    - web_servers

- name: Database configuration
  hosts: db_servers
  become: true
  roles:
    - db_servers

- name: File configuration
  hosts: file_servers
  become: true
  roles:
    - file_servers         
...
