# ansible playbook: server_config.yml
# Usage: $ ansible-playbook server_config.yml
# Note: see [inventory] and [ansible.cfg] for preset details

---

Add plays here
```
---
- name: Install and configure Apache
  hosts: all
  become: true

  tasks:
  - name: Install Apache on Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"
  - name: install php on apache
      apt:
       name: php
       state: present
     when: ansible_distribution == "Ubuntu"
  - name: Install Apache on OracleLinux
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "OracleLinux"

  - name: Start and enable Apache on Ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Start and enable Apache on OracleLinux
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "OracleLinux"
```
 
...
